<?php
/**
 * PossibleOrderlinesPostModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenOrderlines
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen Orderlines
 *
 * SayWhen Orderlines API Documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SayWhenOrderlines\Model;

use \ArrayAccess;

/**
 * PossibleOrderlinesPostModel Class Doc Comment
 *
 * @category    Class */
/**
 * @package     SayWhenOrderlines
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PossibleOrderlinesPostModel implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PossibleOrderlinesPostModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'previous_questions' => 'string',
        'next_question' => 'string',
        'collected_order_line_references' => 'string',
        'fields_object' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'previous_questions' => 'previousQuestions',
        'next_question' => 'nextQuestion',
        'collected_order_line_references' => 'collectedOrderLineReferences',
        'fields_object' => 'fieldsObject'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'previous_questions' => 'setPreviousQuestions',
        'next_question' => 'setNextQuestion',
        'collected_order_line_references' => 'setCollectedOrderLineReferences',
        'fields_object' => 'setFieldsObject'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'previous_questions' => 'getPreviousQuestions',
        'next_question' => 'getNextQuestion',
        'collected_order_line_references' => 'getCollectedOrderLineReferences',
        'fields_object' => 'getFieldsObject'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['previous_questions'] = isset($data['previous_questions']) ? $data['previous_questions'] : null;
        $this->container['next_question'] = isset($data['next_question']) ? $data['next_question'] : null;
        $this->container['collected_order_line_references'] = isset($data['collected_order_line_references']) ? $data['collected_order_line_references'] : null;
        $this->container['fields_object'] = isset($data['fields_object']) ? $data['fields_object'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets previous_questions
     * @return string
     */
    public function getPreviousQuestions()
    {
        return $this->container['previous_questions'];
    }

    /**
     * Sets previous_questions
     * @param string $previous_questions Previous Question and Answers in JSON format
     * @return $this
     */
    public function setPreviousQuestions($previous_questions)
    {
        $this->container['previous_questions'] = $previous_questions;

        return $this;
    }

    /**
     * Gets next_question
     * @return string
     */
    public function getNextQuestion()
    {
        return $this->container['next_question'];
    }

    /**
     * Sets next_question
     * @param string $next_question Next Question and Answers in JSON format
     * @return $this
     */
    public function setNextQuestion($next_question)
    {
        $this->container['next_question'] = $next_question;

        return $this;
    }

    /**
     * Gets collected_order_line_references
     * @return string
     */
    public function getCollectedOrderLineReferences()
    {
        return $this->container['collected_order_line_references'];
    }

    /**
     * Sets collected_order_line_references
     * @param string $collected_order_line_references Collected Orderline References in JSON format
     * @return $this
     */
    public function setCollectedOrderLineReferences($collected_order_line_references)
    {
        $this->container['collected_order_line_references'] = $collected_order_line_references;

        return $this;
    }

    /**
     * Gets fields_object
     * @return string
     */
    public function getFieldsObject()
    {
        return $this->container['fields_object'];
    }

    /**
     * Sets fields_object
     * @param string $fields_object Fields and Values in JSON format
     * @return $this
     */
    public function setFieldsObject($fields_object)
    {
        $this->container['fields_object'] = $fields_object;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\SayWhenOrderlines\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\SayWhenOrderlines\ObjectSerializer::sanitizeForSerialization($this));
    }
}
